[set]
# VLSI-05
# batch_size = 64
# device = cuda:0,1
# num_workers = 0


# VLSI-02
# batch_size = 1
# device = cuda:0,1
# num_workers = 0

# Autodl
batch_size = 128
#512
device = cuda:0
#0,1,2,3,4,5,6,7
num_workers = 15

user = root
compress = scripts/YAML/prune_quant_sensitivity_module.yaml
epoch_start_valtest = 30
extract = false
;resumed_checkpoint_path = false

[fine]
threshold_lr_x = 100
lambda = 0.5
bias = 0
