[set]

# VLSI-05

# batch_size = 64
# num_workers = 0
# device_ids = [0, 1]

#VLSI-02

# batch_size = 32
# num_workers = 0
# device_ids = [0,1,2,3]

# Autodl

batch_size = 1
# 512
device_ids = [0]
num_workers = 4

user = fuyz
compress = scripts/YAML/quant_module.yaml
resumed_checkpoint_path = Extract/branch_consecutive_frame_serialrestore_trainth3_fuyz_lambda0_bias0_1_threshold_lr_x100_threshold_lr_factor0_5_sp2th_init3_reset_th_False_compress_scripts_YAML_quant_module_yaml/run/run_0/models/_epoch-14_best.pth.tar
resumed_reset_th = false
resumed_reset_optim = true
epoch_start_valtest = 30
extract = true
extract_origin = true

[fine]
prefix = branch_consecutive_frame_serialrestore_extract
requires_grad = true
lambda = 0.1

sp2th_amp = [20, 20, 20, 20, 20, 20, 20, 20]
# sp2th_min = [1, 1, 1, 1, 1, 1, 1, 1]
sp2th_min = [0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1]
sp2th_init = [6, 6, 6, 6, 6, 6, 6, 6]

epoch_start_th_learn = 20
threshold_lr_x = 100
threshold_lr_factor = 0.5
bias = 0.1

